[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"


[dependencies]

tokio = {version = "*", featur = ["rt-multi thread", "macros"]}
tide = "*"
serde = {version = "1.0", featur = ["derive"]}
serde_json = "1.0"
